# Generated by Django 3.1.5 on 2021-01-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glemping', '0004_auto_20210120_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='season',
            field=models.CharField(max_length=100),
        ),
    ]
