# Generated by Django 3.1.5 on 2021-01-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glemping', '0008_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
