# Generated by Django 3.1.5 on 2021-01-25 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('glemping', '0010_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='We need this to send booking data', max_length=254),
        ),
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(default='First name', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(default='12345678', max_length=8),
        ),
        migrations.AddField(
            model_name='reservation',
            name='surname',
            field=models.CharField(default='Last name', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
