# Generated by Django 3.1.5 on 2021-01-25 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glemping', '0011_auto_20210125_1958'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('date', 'available')},
        ),
    ]
