# Generated by Django 3.1.5 on 2021-02-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glemping', '0013_auto_20210205_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='surname',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
