# Generated by Django 3.1.5 on 2021-02-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glemping', '0016_auto_20210205_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(default='5', max_length=5),
        ),
    ]
